'use client';
import {awards,patents,projects,research,skills,stats,timeline} from '@/data/site';import {Button,Card,Section} from './ui';import {Download} from 'lucide-react';
export function Hero(){return <section className="grid-bg relative overflow-hidden"><div className="absolute left-1/2 top-20 h-72 w-72 rounded-full bg-orange/20 blur-3xl"/><div className="mx-auto grid min-h-[82vh] max-w-7xl items-center gap-10 px-4 py-20 md:grid-cols-[1.2fr_.8fr]"><div><p className="font-semibold uppercase tracking-[.25em] text-orange">Engineering • Innovation • R&D</p><h1 className="mt-5 text-5xl font-bold tracking-tight md:text-7xl">Engineering Innovation Leader for industrial product breakthroughs.</h1><p className="mt-6 max-w-2xl text-lg text-slate-600 dark:text-slate-300">Placeholder portfolio focused on mechanical design, mining equipment, mill liners, screening systems, patent strategy, FEA, CAD, material engineering, and design validation.</p><div className="mt-8 flex flex-wrap gap-3"><Button href="/projects">View case studies</Button><Button href="/resume"><Download size={18}/>Download portfolio</Button></div></div><Card><h3 className="text-2xl font-bold">Innovation Pipeline</h3><p className="mt-3 text-slate-600 dark:text-slate-300">Discovery → concept → simulation → prototype → field validation → patent capture → launch.</p><div className="mt-6 grid gap-3">{['Wear technology','Validated design systems','Technology roadmap','Patent portfolio'].map(x=><span className="rounded-2xl bg-white/60 p-3 dark:bg-white/10" key={x}>{x}</span>)}</div></Card></div></section>}
export function Stats(){return <Section title="Measured engineering impact" eyebrow="Outcomes"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{stats.map(([n,l])=><Card key={l}><div className="text-4xl font-bold text-orange">{n}</div><p>{l}</p></Card>)}</div></Section>}
export function Skills(){return <Section title="Key engineering skills" eyebrow="Capabilities"><div className="flex flex-wrap gap-3">{skills.map(s=><span className="rounded-full border border-slate-200 px-4 py-2 dark:border-white/15" key={s}>{s}</span>)}</div></Section>}
export function ProjectGrid(){return <div className="grid gap-6 md:grid-cols-3">{projects.map(p=><Card key={p.title}><img alt="Project diagram placeholder" src={p.image} className="mb-5 h-40 w-full rounded-2xl object-cover"/><p className="text-sm font-semibold text-orange">{p.category}</p><h3 className="mt-2 text-xl font-bold">{p.title}</h3><p className="mt-3 text-slate-600 dark:text-slate-300">{p.description}</p><div className="mt-4 flex flex-wrap gap-2">{p.tech.map(t=><span className="rounded-full bg-slate-100 px-3 py-1 text-xs dark:bg-white/10" key={t}>{t}</span>)}</div><div className="mt-5 flex gap-3"><a href={p.github}>GitHub</a><a href={p.pdf}>PDF</a></div></Card>)}</div>}
export function Timeline(){return <div className="space-y-5">{timeline.map(([y,t])=><Card key={y}><div className="flex gap-5"><b className="text-orange">{y}</b><p>{t}</p></div></Card>)}</div>}
export function PatentCards(){return <div className="grid gap-6 md:grid-cols-2">{patents.map(p=><Card key={p.title}><p className="text-sm text-orange">{p.status}</p><h3 className="text-2xl font-bold">{p.title}</h3><p className="mt-3">{p.abstract}</p><ul className="mt-4 list-disc pl-5">{p.benefits.map(b=><li key={b}>{b}</li>)}</ul><div className="mt-5 rounded-2xl border border-dashed p-8 text-center">Technical diagram placeholder</div></Card>)}</div>}
export function ResearchList(){return <div className="grid gap-6 md:grid-cols-2">{research.map(r=><Card key={r}><h3 className="text-xl font-bold">{r}</h3><p className="mt-3 text-slate-600 dark:text-slate-300">Publication / whitepaper placeholder with downloadable PDF support.</p></Card>)}</div>}
export function Awards(){return <Section title="Awards and recognition" eyebrow="Leadership"><div className="grid gap-4 md:grid-cols-3">{awards.map(a=><Card key={a}>{a}</Card>)}</div></Section>}
