'use client';
import Link from 'next/link';import { motion,useScroll } from 'framer-motion';import { ArrowUp,Download,ExternalLink,FileText,Lightbulb,Menu,Search,X } from 'lucide-react';import { useEffect,useState } from 'react';
export const nav=['Home','About','Experience','Projects','Patents','Research','Blog','Resume','Contact'];
export function Navbar(){const[open,setOpen]=useState(false);const[dark,setDark]=useState(false);useEffect(()=>{const d=localStorage.theme==='dark'||(!localStorage.theme&&matchMedia('(prefers-color-scheme: dark)').matches);setDark(d);document.documentElement.classList.toggle('dark',d)},[]);return <header className="sticky top-0 z-50 border-b border-slate-200/30 bg-white/70 backdrop-blur-xl dark:bg-navy/70"><nav className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3"><Link href="/" className="font-bold tracking-tight">Innovation<span className="text-orange">Leader</span></Link><div className="hidden gap-5 md:flex">{nav.map(n=><Link key={n} href={n==='Home'?'/':`/${n.toLowerCase()}`} className="text-sm text-slate-600 hover:text-orange dark:text-slate-300">{n}</Link>)}</div><div className="flex items-center gap-2"><button aria-label="Toggle theme" onClick={()=>{localStorage.theme=dark?'light':'dark';setDark(!dark);document.documentElement.classList.toggle('dark',!dark)}} className="rounded-full border px-3 py-1 text-sm">{dark?'Light':'Dark'}</button><button aria-label="Menu" className="md:hidden" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></nav>{open&&<div className="grid gap-2 px-4 pb-4 md:hidden">{nav.map(n=><Link onClick={()=>setOpen(false)} key={n} href={n==='Home'?'/':`/${n.toLowerCase()}`}>{n}</Link>)}</div>}</header>}
export function ScrollProgress(){const{scrollYProgress}=useScroll();return <motion.div style={{scaleX:scrollYProgress}} className="fixed left-0 top-0 z-[70] h-1 w-full origin-left bg-orange"/>}
export function BackToTop(){return <button aria-label="Back to top" onClick={()=>scrollTo({top:0,behavior:'smooth'})} className="fixed bottom-5 right-5 z-50 rounded-full bg-orange p-3 text-white shadow-glow"><ArrowUp size={18}/></button>}
export function CustomCursor(){const[pos,setPos]=useState({x:-20,y:-20});useEffect(()=>{const f=(e:MouseEvent)=>setPos({x:e.clientX,y:e.clientY});addEventListener('mousemove',f);return()=>removeEventListener('mousemove',f)},[]);return <div className="cursor-dot hidden lg:block" style={{left:pos.x,top:pos.y}}/>}
export function Section({eyebrow,title,children}:{eyebrow?:string;title:string;children:React.ReactNode}){return <section className="mx-auto max-w-7xl px-4 py-20"><p className="font-semibold uppercase tracking-[.25em] text-orange">{eyebrow}</p><h2 className="mt-3 text-3xl font-bold md:text-5xl">{title}</h2><div className="mt-10">{children}</div></section>}
export function Card({children}:{children:React.ReactNode}){return <motion.div initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="glass rounded-3xl p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-glow">{children}</motion.div>}
export function Button({href,children}:{href:string;children:React.ReactNode}){return <Link href={href} className="inline-flex items-center gap-2 rounded-full bg-navy px-5 py-3 font-semibold text-white shadow-glow dark:bg-white dark:text-navy">{children}</Link>}
export const Icons={Download,ExternalLink,FileText,Lightbulb,Search};
